name: SASgf-test-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - nodejs
#  - openjdk
  - pip:
    - jupyterlab
    - nbgitpuller
    - sas_kernel
    - saspy
    - swat
    - pandas
    - numpy
    - sphinx
    - jupyter-book
    - myst-nb
    - pyppeteer

