#!/bin/bash

set -ex

pip install swat

# build Jupyterlab
jupyter lab build --dev-build=False --minimize=False

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/workspace.json
